### ISSUE TITLE
Constantly getting sync notication

### ISSUE THREAD

**Issue by OmgImAlexis** [andryou/scriptsafe#143]
Since the last update I'm getting the notification about syncing being finished every 30 minutes or so.

**Comment by andryou** [comment]
Thanks for submitting this issue; is this with regular browsing without adding any domains to lists (e.g. allow/trust/deny/distrust)? Because ScriptSafe is set so that after an options change or list modification, it will sync the latest changes within 30 seconds.

A fix would be to untick Show Import Sync Notification and/or Show Sync Notification, but I'll try to do some testing on my end when I get a break from the festivities to see if I can recreate this.

**Comment by OmgImAlexis** [comment]
I'm guessing this was in the last update then since it never use to send me notifications. This is with normal usage with me just reinstalling it so nothing was synced before now. I guess this is normal behaviour now?


![screen shot 2016-12-25 at 9 43 54 am](https://cloud.githubusercontent.com/assets/6525926/21469099/0a4bbe5a-ca89-11e6-87b6-05eb3509826c.png)

**Comment by andryou** [comment]
Yes it would be normal behaviour if you changed some options or whitelisted/blacklisted a domain (or fingerprint option for a domain). Did you do a fresh install? (as it is enabled by default) Because I find it strange it's sending you notifications all of a sudden otherwise. (Thanks for the screencap)

**Comment by OmgImAlexis** [comment]
Yeah I did do a fresh install as when I tried to sync Chrome I had so many broken extensions that Chrome kept on crashing.

I did notice that the behaviour must have changed since I first started using it as I've never gone into any settings at all and was never shown the message before.

**Comment by andryou** [comment]
Ah that would explain it!

One of my guesses is that perhaps previously you did not enable syncing (the "OK/Cancel" prompt that appears upon first-run; clicking on OK would enable syncing and hence the notifications, otherwise clicking on Cancel or dismissing it would leave syncing as disabled).

**Comment by OmgImAlexis** [comment]
That may be it. Okay I'll close this, thanks for the support especially on christmas. 👍
