### ISSUE TITLE
(Title="") element description missing

### ISSUE THREAD

**Issue by AdamF001** [andryou/scriptsafe#169]
With canvas protection blank readout the title for the Canvas Fingerprint (1) on mouse hover shows nothing, it might not be a problem but its missing it. (Chrome 56 x64, Windows 7 x64)
![no title](https://cloud.githubusercontent.com/assets/24633575/22376309/5d108414-e4a5-11e6-825b-6b94d93ab620.png)

**Comment by andryou** [comment]
Yup, this is intentional as the items are domain-specific and fingerprinting functions could be attempted by scripts hosted on the current domain as well as other domains/subdomains. In other words, you'll need to click on it to expand the list of domains which you can hover over and view the readouts. (related to #168 :))

**Comment by AdamF001** [comment]
Oh okay, just because as posting before the battery fingerprinting shows all the included GetBattery() elements one by one but this one is just empty, but alright ^^ keep doin what you doin!
