### ISSUE TITLE
Cursor is not aligned with buttons

### ISSUE THREAD

**Issue by Syphdias** [andryou/scriptsafe#189]
http://i.imgur.com/8SrZ0Z5.png

**Comment by Jurph** [comment]
I am also having this problem but only on a dual-monitor setup where my browser is in the portrait-oriented monitor.  I suspect what's happening is that the extension is reading a system property like "horizontal_lines" from some system resource, and basing all offsets for the pointers on that.  On a dual-resolution setup (or possibly a landscape/portrait setup) the system resource is referring to a value that is appropriate for the primary monitor but not for the second one -- either because its "horizontal_lines" value is now stored in the "vertical_lines" value, or because the value is different for each monitor.  

@andryou I'm happy to help test this, since I've been able to reproduce it on my setup.

**Comment by Syphdias** [comment]
Sadly this is a chrome issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=659642
