### ISSUE TITLE
Unexpected Behaviour ?

### ISSUE THREAD

**Issue by PrimeXPC** [andryou/scriptsafe#287]
With 1.0.9.5 ScriptSafe was functioning as I expected and blocking all scripts. These are the exported rules I had for Yahoo. 

"yahoo.com","yep.video.yahoo.com","dcarack01.vpg.cdn.yimg.com","yrtas.btrll.com","mbp.yimg.com","dcarack08.vpg.cdn.yimg.com","dcarack07.vpg.cdn.yimg.com","dcarack09.vpg.cdn.yimg.com","mibrack02.vpg.cdn.yimg.com","s.yimg.com","dcarack04.vpg.cdn.yimg.com","dcarack06.vpg.cdn.yimg.com"

After updating to 1.0.9.6 these are the only rules I can apply.

"yahoo.com","s.yimg.com"

The site is working fine it's just allowing all scripts after allowing these two with no further control. Unsure what could have happened. Reverted back to 1.0.9.5 and it did no good. Deleted all rules and double checked settings. Tested on other sites and the same applies. Allow the top domain and no further control or requests are shown. I'm just setting to allow with none trusted. Not sure if this is a bug or only on my end.

**Comment by andryou** [comment]
Do you have an ad blocker installed? One possible explanation is that after
the update, the priority changed and the other extension is blocking the
request before it gets to ScriptSafe. Is there a test page I can take a
look at?

On Dec 4, 2017 6:46 PM, "PrimeXPC" <notifications@github.com> wrote:

With 1.0.9.5 ScriptSafe was functioning as I expected and blocking all
scripts. These are the exported rules I had for Yahoo.

"yahoo.com","yep.video.yahoo.com","dcarack01.vpg.cdn.yimg.com","
yrtas.btrll.com","mbp.yimg.com","dcarack08.vpg.cdn.yimg.com","
dcarack07.vpg.cdn.yimg.com","dcarack09.vpg.cdn.yimg.com","mibrack02.vpg.cdn.
yimg.com","s.yimg.com","dcarack04.vpg.cdn.yimg.com","dcarack
06.vpg.cdn.yimg.com"

After updating to 1.0.9.6 these are the only rules I can apply.

"yahoo.com","s.yimg.com"

The site is working fine it's just allowing all scripts after allowing
these two with no further control. Unsure what could have happened.
Reverted back to 1.0.9.5 and it did no good. Deleted all rules and double
checked settings. Tested on other sites and the same applies. Allow the top
domain and no further control or requests are shown. I'm just setting to
allow with none trusted. Not sure if this is a bug or only on my end. Any
input would be welcome.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/andryou/scriptsafe/issues/287>, or mute the thread

**Comment by PrimeXPC** [comment]
That's it. I had already thought of that and tried disabling uBlock per page and it made no difference. I just disabled the whole extension and tested and now all is right. Went back enabled uBlock and now I can just disable it per page and ScriptSafe will show all requests.

Anyway possible to give ScriptSafe priority over uBlock ? If not I may have to look in a different ad blocker and maybe that will work.

Thanks.

**Comment by andryou** [comment]
Good to hear! I think I'll add this to the FAQs page on my site for anyone else running into this.

I use uBlock Origin religiously on all my devices: it's an excellent extension by an excellent developer (gorhill). I haven't really run into any issues with it and ScriptSafe enabled at the same time. uMatrix by the same developer is excellent as well.

In terms of assigning priority, I believe that browsers assign higher priority to older extensions. So for example if you backup your uBlock settings, uninstall uBlock, reinstall and import your settings, theoretically ScriptSafe would have higher priority.

**Comment by PrimeXPC** [comment]
Will give that a try and Thanks for the info.  👍

**Comment by andryou** [comment]
Will close this issue, but feel free to create another if you run into anything!
