### ISSUE TITLE
Same domain allows subdomains and more

### ISSUE THREAD

**Issue by Aybee** [andryou/scriptsafe#32]
There are some bugs  and great differences between v1.0.7.6 I think.

- Same domain seems to also allow subdomains.
- Why are there so many WEBBUGS?
- On youtube you can not see the preview thumbs (you  have to allow i.ytimg.com but it's not visible in dropdown)
- What is this blob() - blob:https://www.youtube.com...

Since v1.0.7.7 I can not realy find a setting that acts as I expect. Maybe I do not understand the new options?

**Comment by andryou** [comment]
Thanks for the report!

> Same domain seems to also allow subdomains.

That is the expected behaviour; "Respect Same-Domain" allows resources from everything on the same root domain of the page you're visiting. If security/privacy is very important, you'd want this disabled. But if you want to avoid breaking pages out of the box, this setting is handy.

> Why are there so many WEBBUGS?

This is an issue I found last night, experienced only if you also ticked Images to be disabled/removed. This will be fixed in the next release (v1.0.7.9), which I'm thinking of doing relatively sooner than later as I have a good number of updates ready to go. I'm still doing testing to make this release as solid as possible. I appreciate your feedback!

> On youtube you can not see the preview thumbs (you have to allow i.ytimg.com but it's not visible in dropdown)

This is related to the above issue regarding images being classified as webbugs (which happens only if you ticked Images to be disabled/removed)

> What is this blob() - blob:https://www.youtube.com...

Could you provide a link for me to test this out? Thanks! :)

**Comment by Aybee** [comment]
**Blob**:
Sample page
https://www.youtube.com/watch?v=ZCMpnWqdZw4
bloburl stackoverflow
http://stackoverflow.com/questions/33389001/what-is-blob-in-the-video-src-bloburl

I'm not sure if I should post my settings every time. Here is my whitelist
```
**.googlevideo.com
**.ytimg.com
google.com
google.de
```
**Subdomains**:
I'm not sure but I think the behavior was another in earlier versions. Shall I make a feature request out of this one?

**Comment by andryou** [comment]
**Blob:** Thanks! Very interesting. From the Stackoverflow page: "A blob: URL does not refer to data the exists on the server, it refers to data that your browser currently has in memory, for the current page. It will not be available on other pages, it will not be available in other browsers, and it will not be available from other computers." So this means that once it's loaded. From what I can tell at this point in time, in order to prevent blobs the tab must not be granted inline script permissions. I'll need to look into this further to see if it's possible to stop blobs from loading, but it may be difficult if inline script has been granted for the tab.

**Subdomains:** the behaviour was incorrect in v1.0.7.7 (quickly reported and pointed out in #25), but in all other versions it remained the same: if viewing domain.com, it would consider abc.domain.com and even abc.def.domain.com as the "same domain" and therefore allow resources from these domains (including the tab's domain) to load (this I'm certain of).

**Comment by Aybee** [comment]
Thank you for your reply. 

I will make a feature request for same domain subdomain topic when I think I can not live without it :smiley: 

Don't know if it is necessary to work on this blob thing for now. I just wanted to report it as it was strange to see this blob thing without knowing what this is and where it comes from. Maybe its better to show the original domain behind the blob so we can see it without the need of hovering over the blob.

**Comment by andryou** [comment]
Thinking about this, maybe I can change the current setting into a dropdown: Disabled, Same Subdomain, and Same Domain

Same Domain will be the current behaviour, but Same Subdomain will only allow resources on the same exact subdomain as the current page (e.g. www.domain.com/*)

Let me know if this sounds good :)

**Comment by Aybee** [comment]
Same Subdomain sounds strange to me. What do you think about

1. Disabled
2. Same Domain (default)
3. Same Domain strict (new)

**Comment by andryou** [comment]
How's this?

![2016-06-09 13_14_23](https://cloud.githubusercontent.com/assets/4351175/15939066/2291557e-2e44-11e6-9403-122ac3451427.png)

**Comment by Aybee** [comment]
Don't know. I think definitons are
```
example.org     => domain
sub.example.org => domain, subdomain
```
So every subdomain also is a domain, but a domain like examlpe.org is not a subdomain. So if you follow this you have to use maybe
```
strict blocking - disabled             => do not allow actual domain
less blocking   - same domain          => allow actual domain only (root domain?, no subs?)
loose blocking  - same domain and subs => allow actual domain and its subdomains
```

**Comment by andryou** [comment]
Thanks! Here's what I have:

Option label: Respect Same-Domain

Choices:
* Disabled
* Strict - allow same domain only
* Loose - allow same domain and subdomains

**Comment by Aybee** [comment]
I think this will be ok. Don't know what others think about it.

BTW Two questions:
1. With strict and I'm on **sub.example.org**. This will only allow sub.example.org? Not example.org? (it should be this way)
2. And with Loose on **sub.example.org**, this will allow itself and **sub**.sub.example.org? Or will this also allow **another.**example.org?

**Comment by andryou** [comment]
> 1. With strict and I'm on sub.example.org. This will only allow sub.example.org? Not example.org? (it should be this way)

Yes, with **Strict**, when visiting a page on sub.example.org, it will only allow sub.example.org. If a resource being loaded is on example.org, it will be blocked.

> 2. And with Loose on sub.example.org, this will allow itself and sub.sub.example.org? Or will this also allow another.example.org?

Yes, with **Loose**, when visiting a page on sub.example.org, it will allow: sub.example.org, sub.sub.example.org, another.example.org, and example.org (anything on example.org)

**Comment by andryou** [comment]
v1.0.7.10 has been published with everything discussed in this issue. Please close this issue if it looks good!

**Comment by Aybee** [comment]
Thank you very much. Seems to be ok so far. Now I'm testing the betas and will report when I find something strange.
