### ISSUE TITLE
Scripts Not separated, causes issues

### ISSUE THREAD

**Issue by askingt** [andryou/scriptsafe#62]
For some sites, I'll see a script listed as such:
asset0.website.com (2)
or 
assest1.website.com (11)

Is there a way to list those separately?  One of the scripts contained is necessary and others are full of junk ads and spam and sometimes worse but at the current settings, there is no way to separate them.

Perhaps create an option, like an button to expand and select each item so you can check which ones you want to change permissions on, for those who need to select only one of the items in the group?

Thank you.

**Comment by andryou** [comment]
@askingt can you provide a test page? Thanks!

**Comment by NM8Services** [comment]
I was just coming to ask about something related to the same issue using a social media site for clients and on the photo upload page there are tons of things that come up all together with the photo uploads which is the one thing I need to allow. I was trying to figure out how to contact you privately since this occurs in the administration area of a site.

**Comment by andryou** [comment]
Unfortunately it isn't possible to allow only one script from a domain to load without allowing all (sorry for the delayed reply)
